name: Build LaTeX document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y texlive-full

    - name: Build LaTeX document
      run: |
        cd Crypto_RSA
        make
